description: "A queer, female-led independent feature film about a struggling digital artist who seeks revenge when her work is stolen by an influential curator."
email: "undertheinfluencermovie@gmail.com"
